targetCustomizations:
- name: aks
  helm:
    values:
      ingress:
        name: aks-ingress
        class: nginx
        annotations:
           nginx.ingress.kubernetes.io/ssl-redirect: "false"
           nginx.ingress.kubernetes.io/use-regex: "true"
  clusterSelector:
    matchLabels:
      cloud: aks

